MDScreen:
    size: 500, 500

    MDBoxLayout:
        id: scre
        orientation: 'vertical'
        md_bg_color: '#B6EADA'

        MDLabel:
            id:text
            color: "#03001C"
            font_style: "H3"
            text: 'Krish'
            size_hint: 1,1
            halign: 'center'

        MDRaisedButton:
            id: btn
            text: "Dark Mode"
            md_bg_color: "#301E67"
            text_color: '#B6EADA'
            on_press: app.toggle() 